aws:
  region: ca-central-1
  serviceAccount:
    name: external-secrets
    namespace: external-secrets

cloudflare:
  ssmKey: ""
  namespace: external-dns
  refreshInterval: 1h
  secretName: cloudflare-api-key
  secretKey: cloudflare_api_key

slack:
  ssmKey: ""
  namespace: argocd
  refreshInterval: 1h
  secretName: argocd-notifications-secret
  secretKey: slack-token
