aws:
  region: ca-central-1
  serviceAccount:
    name: external-secrets
    namespace: external-secrets

cloudflare:
  ssmKey: ""
  namespace: external-dns
  refreshInterval: 1h
  secretName: cloudflare-api-key
  secretKey: cloudflare_api_key

slack:
  - ssmKey: ""
    namespace: argocd
    refreshInterval: 1h
    secretName: argocd-notifications-secret
    secretKey: slack-token
  - ssmKey: ""
    namespace: argo-rollouts
    refreshInterval: 1h
    secretName: argo-rollouts-notification-secret
    secretKey: slack-token
