# service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
<<<<<<< HEAD
  name: gitops-demo-frontend
automountServiceAccountToken: true
=======
  name: gitops-frontend
automountServiceAccountToken: true
>>>>>>> main
